[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
flowtip_program = "2ZxirQjK8vJ5yvGWbX3XGEybE6wBiFFCBzPwJc9V3fhm"

[programs.devnet]
flowtip_program = "2ZxirQjK8vJ5yvGWbX3XGEybE6wBiFFCBzPwJc9V3fhm"

[programs.mainnet]
flowtip_program = "2ZxirQjK8vJ5yvGWbX3XGEybE6wBiFFCBzPwJc9V3fhm"

[registry]
url = "https://api.anchor.so"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\romil\\.config\\solana\\id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/flowtip-program"
]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false 